### PR TITLE
Correcting hotfolder crashed

### LINKED ISSUE #46: [BUG] Hotfolder crashing with multiple files
**Describe the bug**
If you throw in multiple files into the hotfolder the application just crashes

**To Reproduce**
1. Go to the settings
2. Go to the hotfolder tab
3. Create a new hotfolder configuration (Click on continue on the error message #44)
4. Throw multiple files into the hotfolder 

**Expected behavior**
The application is working on the files

### PR DESCRIPTION
**Pull request by XanatosX**
The hotfolder should not crash anymore

fix #46

### CODE REVIEW

File: XmlFormatter/src/Formatter/XmlFormatterProvider.cs [hunk 1]
```diff
@@ -107,13 +107,42 @@ private async void FormatFile(string inputFilePath, string outputName, SaveOptio
...
             });
 
+            if (fileToConvert == null)
+            {
+                return;
+            }
+
             FireEvent("Saving", "Saving ...");
-            await Task.Run(() => fileToConvert.Save(outputName, options));           
+            bool saveSuccess = await Task<bool>.Run(() => {
```
Comment (XanatosX) [inline XmlFormatter/src/Formatter/XmlFormatterProvider.cs]: Codacy Issue found: [Add '.ConfigureAwait(false)' to this call to allow execution to continue in any thread.](https://app.codacy.com/manual/simonaberle/XmlFormatter/pullRequest?prid=5090949)

**Comment by XanatosX** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 2
           

Complexity increasing per file
==============================
- XmlFormatter/src/DataContainer/HotfolderTask.cs  1
- XmlFormatter/src/Hotfolder/HotfolderManager.cs  1
- XmlFormatter/src/Formatter/XmlFormatterProvider.cs  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/simonaberle/XmlFormatter/pullRequest?prid=5090949&bid=16746769)

File: XmlFormatter/src/Hotfolder/HotfolderManager.cs [hunk 2]
```diff
@@ -109,7 +118,43 @@ private void Watcher_Changed(object sender, FileSystemEventArgs e)
...
+            if (tasksToDo.Count == 0)
+            {
+                return true;
+            }
+
+            foreach (HotfolderTask task in tasksToDo)
+            {
+                ConvertFile(task.Configuration, task.InputFile);
+            }
+            return await AsyncConvertFiles();
```
Comment (XanatosX) [inline XmlFormatter/src/Hotfolder/HotfolderManager.cs]: Codacy Issue found: [Add '.ConfigureAwait(false)' to this call to allow execution to continue in any thread.](https://app.codacy.com/manual/simonaberle/XmlFormatter/pullRequest?prid=5090949)
